export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_REQUEST = 'FETCH_NEWS_REQUEST';
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE';

export const FETCH_MARKET_SUCCESS = 'FETCH_MARKET_SUCCESS';
export const FETCH_MARKET_REQUEST = 'FETCH_MARKET_REQUEST';
export const FETCH_MARKET_FAILURE = 'FETCH_MARKET_FAILURE';

export const FETCH_INVESTMENTS_SUCCESS = 'FETCH_INVESTMENTS_SUCCESS';
export const FETCH_INVESTMENTS_REQUEST = 'FETCH_INVESTMENTS_REQUEST';
export const FETCH_INVESTMENTS_FAILURE = 'FETCH_INVESTMENTS_FAILURE';

export const FETCH_OPPORTUNITIES_SUCCESS = 'FETCH_OPPORTUNITIES_SUCCESS';
export const FETCH_OPPORTUNITIES_REQUEST = 'FETCH_OPPORTUNITIES_REQUEST';
export const FETCH_OPPORTUNITIES_FAILURE = 'FETCH_OPPORTUNITIES_FAILURE';
